# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2
project_name: minecraft-preempt
report_sizes: true
metadata:
  mod_timestamp: "{{ .CommitTimestamp }}"
builds:
  - main: ./cmd/minecraft-preempt
    id: minecraft-preempt
    binary: minecraft-preempt
    flags:
      - -trimpath
    ldflags:
      - -s
      - -w
      ## <<Stencil::Block(minecraft-preemptLdflags)>>
      - -X github.com/jaredallard/minecraft-preempt/v3/internal/version.Version={{ .Version }}
      ## <</Stencil::Block>>
    env:
      - CGO_ENABLED=0
    goarch:
      - amd64
      - arm64
      ## <<Stencil::Block(minecraft-preemptExtraArch)>>

      ## <</Stencil::Block>>
    goos:
      - linux
      - darwin
      ## <<Stencil::Block(minecraft-preemptExtraOS)>>

      ## <</Stencil::Block>>
    ignore:
      - goos: windows
        goarch: arm
    mod_timestamp: "{{ .CommitTimestamp }}"
  - main: ./cmd/minecraft-preempt-agent
    id: minecraft-preempt-agent
    binary: minecraft-preempt-agent
    flags:
      - -trimpath
    ldflags:
      - -s
      - -w
      ## <<Stencil::Block(minecraft-preempt-agentLdflags)>>

      ## <</Stencil::Block>>
    env:
      - CGO_ENABLED=0
    goarch:
      - amd64
      - arm64
      ## <<Stencil::Block(minecraft-preempt-agentExtraArch)>>

      ## <</Stencil::Block>>
    goos:
      - linux
      - darwin
      ## <<Stencil::Block(minecraft-preempt-agentExtraOS)>>

      ## <</Stencil::Block>>
    ignore:
      - goos: windows
        goarch: arm
    mod_timestamp: "{{ .CommitTimestamp }}"
dockers_v2:
  - images:
      ## <<Stencil::Block(extraReleaseOpts)>>
      - ghcr.io/rgst-io/{{ .ProjectName }}
      ## <</Stencil::Block>>
    labels:
      "org.opencontainers.image.title": "{{ .ProjectName }}"
      "org.opencontainers.image.description": "{{ .ProjectName }}"
      "org.opencontainers.image.source": "{{ .GitURL }}"
      "org.opencontainers.image.version": "{{ .Version }}"
      "org.opencontainers.image.created": "{{ .Date }}"
      "org.opencontainers.image.revision": "{{ .FullCommit }}"
      "org.opencontainers.image.licenses": "GPL-3.0"
    platforms:
      - linux/amd64
      - linux/arm64
checksum:
  name_template: "checksums.txt"
snapshot:
  version_template: "{{ incpatch .Version }}-next"
changelog:
  use: git
release:
  prerelease: "auto"
  footer: |-
    **Full Changelog**: https://github.com/rgst-io/minecraft-preempt/compare/{{ .PreviousTag }}...{{ .Tag }}

## <<Stencil::Block(extraReleaseOpts)>>

## <</Stencil::Block>>
