[tool_alias]
dprint = "github:dprint/dprint"

[tools]
dprint = "latest"
golang = "1.26.4"
golangci-lint = "2.12.2"
goreleaser = "latest"
gotestsum = "1.13.0"
shfmt = "latest"
svu = "3.4.0"
git-cliff = "2.13.1"
## <<Stencil::Block(extraTools)>>

## <</Stencil::Block>>

[tasks.build]
description = "Build a binary for the current platform/architecture"
run = "go build -trimpath -o ./bin/ -v ./cmd/..."

[tasks.changelog]
description = "Generate a changelog for the current version"
outputs = ["CHANGELOG.md"]
run = ["git-cliff --config .cliff.toml --output CHANGELOG.md"]

[tasks.fmt]
alias = "format"
description = "Format code"
run = [
	"go mod tidy",
	"golangci-lint fmt",
	"shfmt -w .",
	"dprint fmt '**/*.{json,yaml,yml,md,jsonschema.json}'",
]

[tasks.lint]
description = "Run linters"
run = "golangci-lint run"

[tasks.next-version]
description = """Get the version number that would be released if a release was ran right now.
Pass --rc to get the next release candidate version.
"""
run = ["./.github/scripts/get-next-version.sh"]

[tasks.test]
description = "Run tests"
run = "gotestsum"

## <<Stencil::Block(custom)>>

## <</Stencil::Block>>
